sudo: false
language: python
python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - pypy
  - pypy3

install:
  - pip install tox

script:
  - tox

credentials:
  - &pypi
    provider: pypi
    user: zsimic
    password:
      secure: "J8ut8th4Wj/drhphGlKgOICjUORh+cg0+nbiVbJI6alCWfAhx9gNFPHR7su50Sw4T/LTYY+Dpvn/JXsJEDqCMiEQAFw27iCaxWPZuXfCKin97qLR2fBPV4DrttTM3SQabk36dNqaGoqtrGD1wZH2ei3JZ375tMYy8tt0OBRAt5/lRVu9kcxJemzJKPR6QaiX/JpWbxxo7a3sicurDxw8SpdNcrmjmmy3KDOmdBKa/+2RvUHErrX3MfVX/6fXGpUol/+uEDwbUKfq0UD/31s6Di/pmOGp+u5nVO+08NxHyJAC2Z+2IC7yGpIYqMFsU2yPJJlV+JbGyH4orDIvLvR3LcOiIFTALTqlbwDT0/BP0KTOdR++1biC/MmPTYyoWg/Rhmz2swAJuDhzxZTcVq4HCbvJQt2by5teWAE/CmAZBoVPENFoH0HU5r661aBqdOkCMrUqtwCKv1kXasU1udlqneC1Xus+MH7Jm6A+PCtWlfh00qjaBVVE/tuFELjOVMei2uiMeGKPchOBDd5lRsLPkX9js6pxZ7+BC7DOKmtbsrYuF4mnJ0KBU1F8uP1RamQkagQ1oVMv7orQk7eKvcGcdaLjVgZy77K4ha6iCO3p6bxDXqrXq7Vr6PYMnvuTfeH8Hpq2Hy+txEhB6FHGd5UX37c0pV3d7Uvr3Kcf4V7QA6w="

deploy:
  - <<: *pypi
    on:
      python: 2.7
      repo: zsimic/setupmeta
      tags: true
    distributions: "sdist bdist_wheel"
  - <<: *pypi
    on:
      repo: zsimic/setupmeta
      tags: true
    distributions: "bdist_egg"
